swagger: '2.0'
info:
  version: 1.0.0
  title: Customer Relationship
  description: It maintains a range of customer relationship reference information covering aspects.
host: www.infosys.com
basePath: /customer-relationship/v1
securityDefinitions:
  apiClientID:
    type: apiKey
    in: header
    name: X-INFOSYS-Client-Id
    description: The client id obtained from the API manager. This client id must have been registered to use this API by requesting access to it.
  apiClientSecret:
    type: apiKey
    in: header
    name: X-INFOSYS-Client-secret
    description: The client id obtained from the API manager. This client id must have been registered to use this API by requesting access to it.
  apiSecurityToken:
    type: apiKey
    in: header
    name: X-INFOSYS-SECURE-TOKEN
    description: The SAML or JWT end to end trust token retreived from IDAM
security:
  - apiClientID: []
    apiClientSecret: []
  - apiSecurityToken: []
schemes:
  - https
paths:
  '/customers/{customer-id}/banks':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    post:
      tags:
        - register
      summary: Register bank relationship
      operationId: registerCustomerReferenceDataDirectoryEntryReference
      produces:
        - application/json
      parameters:
        - name: customer-id
          in: path
          description: Customer Reference ID
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/ReferenceBase'
      responses:
        '201':
          description: Successfully registerd reference
          schema:
            $ref: '#/definitions/ReferenceBaseWithIdAndRoot'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'    
  '/customers/{customer-id}/associations':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    post:
      tags:
        - register
      summary: Register a customer relationship
      description: 'Register: Customer relationships/association detail'
      operationId: registerCustomerReferenceDataDirectoryRelationship
      produces:
        - application/json
      parameters:
        - name: customer-id
          in: path
          description: Customer Reference Data Directory Entry Reference
          required: true
          type: string
        - in: body
          name: body
          required: false
          schema:
            $ref: '#/definitions/CustomerAssociationBase'
      responses:
        '201':
          description: Successfully registered an association
          schema:
            $ref: '#/definitions/CustomerAssociationBaseWithIdAndRoot'      
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error' 
  '/customers/{customer-id}/demographics':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    post:
      tags:
        - register
      summary: Register demographic details
      operationId: registerCustomerReferenceDataDirectoryDemographic
      produces:
        - application/json
      parameters:
        - name: customer-id
          in: path
          description: Customer Reference Data Directory Entry Reference
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/DemographicBase'
      responses:
        '201':
          description: Successfully registered a demographic.
          schema:
            $ref: '#/definitions/DemographicBaseWithIdAndRoot'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error' 
  '/customers/{customer-id}/bank-relations':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'  
    post:
      tags:
        - register
      summary: Register bank relationship
      operationId: registerCustomerReferenceDataDirectoryBankRelationship
      produces:
        - application/json
      parameters:
        - name: customer-id
          in: path
          description: Customer Reference Data Directory Entry Reference
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/BankRelationsBase'
      responses:
        '201':
          description: Successfully registerd a bank relation
          schema:
            $ref: '#/definitions/BankRelationsBaseWithIdAndRoot'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error' 
  '/customers/control-records':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    get:
      tags:
        - retrieve
      summary: Retrieve Control Record Ids.
      operationId: RetrieveCustomerReferenceManagementReferenceIds
      produces:
        - application/json
      parameters:
        - name: collection-filter
          in: query
          description: Filter to refine the result set. ex- "customer-reference== 'CR123'"
          required: false
          type: string
      responses:
        '200':
          description: successful
          schema:
            type: array
            items:
              type: string
            example:
              - CREF123
              - CREF345
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'       
  '/customers/behavior-qualifiers/':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    get:
      tags:
        - retrieve
      summary: Retrieve all Behaviour Qualifier
      operationId: RetrieveCustomerReferenceDataManagementBehaviorQualifiers
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful
          schema:
            type: array
            items:
              type: string
            example:
              - reference
              - associations
              - demographics
              - bankrelations      
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'       
  '/customers/{customer-id}/{behavior-qualifier-id}/':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    get:
      tags:
        - retrieve
      summary: Retrieve Behaviour Qualifier Ids.
      operationId: RetrieveBehaviorQualifierReferenceIds
      produces:
        - application/json
      parameters:
        - name: customer-id
          in: path
          description: Customer Reference Data Management Directory Entry Reference
          required: true
          type: string
        - name: behavior-qualifier-id
          in: path
          description: Behavior Qualifier Name. ex- bankrelations
          required: true
          type: string
        - name: collection-filter
          in: query
          description: Filter to refine the result set. ex- "'bankRelationType == RM'"
          required: false
          type: string
      responses:
        '200':
          description: successful
          schema:
            type: array
            items:
              type: string
            example:
              - ODER345
              - ODER789
              - ODER456
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'     
  '/customers/registry/{customer-id}':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    get:
      tags:
        - retrieve
      summary: Retrieve Customer reference data management master record
      operationId: retrieveCustomerReferenceDataDirectory
      produces:
        - application/json
      parameters:
        - name: customer-id
          in: path
          description: Customer Reference Data Management Directory Entry Reference
          required: true
          type: string
      responses:
        '200':
          description: Successfully retrieved Customer Reference Data Directory.
          schema:
            $ref: '#/definitions/RetrieveCustomerReferenceDataManagementRoot'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error' 
  '/customers/{customer-id}/references/{bq-reference-id}/':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    get:
      tags:
        - retrieve
      summary: Retrieve a reference
      operationId: retrieveCustomerReferenceDataDirectoryReferences
      produces:
        - application/json
      parameters:
        - name: customer-id
          in: path
          description: Customer Reference Data Directory Entry Reference
          required: true
          type: string
        - name: bq-reference-id
          in: path
          description: Reference Directory Entry Reference
          required: true
          type: string
      responses:
        '200':
          description: Successfully retrieved Customer Reference Data Directory References.
          schema:
            $ref: '#/definitions/CustomerReferenceDataDirectoryReferences'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'     
  '/customers/{customer-id}/associations/{bq-reference-id}':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    get:
      tags:
        - retrieve
      summary: Retrieve an Associate
      operationId: retrieveCustomerReferenceDataDirectoryAssociates
      produces:
        - application/json
      parameters:
        - name: customer-id
          in: path
          description: Customer Reference Data Directory Entry Reference
          required: true
          type: string
        - name: bq-reference-id
          in: path
          description: Associations Directory Entry Reference
          required: true
          type: string
      responses:
        '200':
          description: Successfully retrieved customer reference data directory associates.
          schema:
            $ref: '#/definitions/CustomerAssociationBaseWithIdAndRoot'    
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'       
  '/customers/{customer-id}/demographics/{bq-reference-id}':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    get:
      tags:
        - retrieve
      summary: Retrieve a Demographic
      operationId: retrieveCustomerReferenceDataDirectoryDemographics
      produces:
        - application/json
      parameters:
        - name: customer-id
          in: path
          description: Customer Reference Data Directory Entry Reference
          required: true
          type: string
        - name: bq-reference-id
          in: path
          description: Demographics Directory Entry Reference
          required: true
          type: string
      responses:
        '200':
          description: Successfully retrieved customer reference data directory demographics.
          schema:
            $ref: '#/definitions/DemographicBaseWithIdAndRoot'      
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error' 
  '/customers/{customer-id}/bankrelations/{bq-reference-id}':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    get:
      tags:
        - retrieve
      summary: Retrieve a Bank Relation
      operationId: retrieveCustomerReferenceDataDirectoryBankRelations
      produces:
        - application/json
      parameters:
        - name: customer-id
          in: path
          description: Customer Reference Data Directory Entry Reference
          required: true
          type: string
        - name: bq-reference-id
          in: path
          description: Bank Relations Directory Entry Reference
          required: true
          type: string
      responses:
        '200':
          description: Successfully retrieved customer reference data directory bank relations.
          schema:
            $ref: '#/definitions/BankRelationsBaseWithIdAndRoot'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'       
  '/customers/{customer-id}/recording':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    post:
      tags:
        - record
      summary: Record a feedback
      operationId: RecordCustomerDataDirectory
      produces:
        - application/json
      parameters:
        - name: customer-id
          in: path
          description: Customer Reference Data Directory Entry Reference
          required: true
          type: string
        - in: body
          name: body
          description: Record control record request payload
          required: true
          schema:
            $ref: '#/definitions/CustomerReferenceDataRecordRequest'
      responses:
        '201':
          description: Successfuly recorded usage against customer directory entry.
          schema:
            $ref: '#/definitions/CustomerReferenceDataRecordResponse'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'       
  '/customers/{customer-id}/requisition':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    put:
      tags:
        - request
      summary: Request a Directory Update
      operationId: RequestCustomerReferenceDataDirectoryUpdate
      produces:
        - application/json
      parameters:
        - name: customer-id
          in: path
          description: Customer Reference Data Directory Entry Reference
          required: true
          type: string
        - in: body
          name: body
          description: Request customer reference request payload
          required: true
          schema:
            $ref: '#/definitions/ReferenceBase'
      responses:
        '200':
          description: Successfully requested a refresh of an existing customer directory entry.
          schema:
            $ref: '#/definitions/ReferenceBaseWithIdAndRoot'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'     
  '/customers/requisition':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'    
    post:
      tags:
        - request
      summary: Requests a Directory Creation
      description: Create a new Customer Reference Data Directory
      operationId: RequestCustomerReferenceDataDirectoryCreate
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Request customer reference request payload
          required: true
          schema:
            $ref: '#/definitions/ReferenceBase'
      responses:
        '201':
          description: Successfully created customer directory entry.
          schema:
            $ref: '#/definitions/ReferenceBaseWithIdAndRoot'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'       
  '/customers/{customer-id}/reference':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    put:
      tags:
        - update
      summary: Update reference data
      operationId: UpdateCustomerReferenceDataDirectory
      produces:
        - application/json
      parameters:
        - name: customer-id
          in: path
          description: Customer Reference Data Directory Entry Reference
          required: true
          type: string
        - in: body
          name: body
          description: Update control record request payload
          required: true
          schema:
            $ref: '#/definitions/ReferenceBaseUpdateRequest'
      responses:
        '200':
          description: Successfully
          schema:
            $ref: '#/definitions/ReferenceBaseWithIdAndRoot'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'       
definitions:
  CustomerReferenceDataRecordRequest:
    type: object
    properties:
      recordingRecordType:
        type: string
        example: Behavior Model Performance Feedback
      recordingRecord:
        type: object
        properties: {}
      recordingRecordDateTime:
        type: string
        example: '2018-08-28T09:00:00'
      empolyeeBusinessUnitReference:
        type: string
        example: EBUR6798
    example:
      recordingRecordType: Behavior Model Performance Feedback
      empolyeeBusinessUnitReference: EBUR6798
      recordingRecordDateTime: '2018-08-28T09:00:00'
      recordingRecord: '{}'
  CustomerReferenceDataRecordResponse:
    type: object
    properties:
      recordingRecordReference:
        type: string
        example: RRR59821735
      recordingRecordStatus:
        type: string
        example: Applied
    example:
      recordingRecordReference: RRR59821735
      recordingRecordStatus: Applied
  CustomerAssociationBase:
    type: object
    properties:
      customerReference:
        type: string
        example: CR3816
      employeeReference:
        type: string
        example: EMPR3816
      associateType:
        type: string
        example: Familial
      associateReference:
        type: string
        example: ASRE4820
      associateObligationDependencyDescription:
        type: string
        example: Legal Assistant Obligation
      associationValidFromTo:
        type: string
        example: 2017-07-01 To 2018-07-31
      productInstanceReference:
        type: string
        example: PRIR5859
      preferredBeneficiary:
        type: string
        example: Father
      proxyRepresentativePowerOfAttorneyReference:
        type: string
        example: PRPA7398
    example:
      associateObligationDependencyDescription: Legal Assistant Obligation
      productInstanceReference: PRIR5859
      associateReference: ASRE4820
      preferredBeneficiary: Father
      employeeReference: EMPR3816
      customerReference: CR3816
      associateType: Familial
      associationValidFromTo: 2017-07-01 To 2018-07-31
      proxyRepresentativePowerOfAttorneyReference: PRPA7398
  CustomerAssociationBaseWithIdAndRoot:
    type: object
    properties:
      customerReferenceDataDirectoryEntryReference:
        type: string
        example: CRDDER679
      associationsDirectoryEntryReference:
        type: string
        example: ADER123
      customerReference:
        type: string
        example: CR3816
      employeeReference:
        type: string
        example: EMPR3816
      associateType:
        type: string
        example: Familial
      associateReference:
        type: string
        example: ASRE4820
      associateObligationDependencyDescription:
        type: string
        example: Legal Assistant Obligation
      associationValidFromTo:
        type: string
        example: 2017-07-01 To 2018-07-31
      productInstanceReference:
        type: string
        example: PRIR5859
      preferredBeneficiary:
        type: string
        example: Father
      proxyRepresentativePowerOfAttorneyReference:
        type: string
        example: PRPA7398
    example:
      associateObligationDependencyDescription: Legal Assistant Obligation
      productInstanceReference: PRIR5859
      associateReference: ASRE4820
      preferredBeneficiary: Father
      employeeReference: EMPR3816
      customerReferenceDataDirectoryEntryReference: CRDDER679
      customerReference: CR3816
      associateType: Familial
      associationValidFromTo: 2017-07-01 To 2018-07-31
      proxyRepresentativePowerOfAttorneyReference: PRPA7398
      associationsDirectoryEntryReference: ADER123
  DemographicBase:
    type: object
    properties:
      customerReference:
        type: string
        example: CSRE3456
      socioEconomicClassification:
        type: string
        example: High
      ethnicityReligion:
        type: string
        example: Christian
      employment:
        type: string
        example: Analyst
      employmentHistory:
        type: string
        example: 2 Years in Google
      educationHistory:
        type: string
        example: Post Graduate From MIT University
      servicingConstraints:
        type: string
        example: Collective
    example:
      employmentHistory: 2 Years in Google
      ethnicityReligion: Christian
      servicingConstraints: Collective
      customerReference: CSRE3456
      socioEconomicClassification: High
      employment: Analyst
      educationHistory: Post Graduate From MIT University
  DemographicBaseWithIdAndRoot:
    type: object
    properties:
      customerReferenceDataDirectoryEntryReference:
        type: string
        example: CRDDER679
      demographicsDirectoryEntryReference:
        type: string
        example: CSRE3456
      customerReference:
        type: string
        example: CSRE3456
      socioEconomicClassification:
        type: string
        example: High
      ethnicityReligion:
        type: string
        example: Christian
      employment:
        type: string
        example: Analyst
      employmentHistory:
        type: string
        example: 2 Years in Google
      educationHistory:
        type: string
        example: Post Graduate From MIT University
      servicingConstraints:
        type: string
        example: Collective
    example:
      employmentHistory: 2 Years in Google
      ethnicityReligion: Christian
      servicingConstraints: Collective
      demographicsDirectoryEntryReference: CSRE3456
      customerReferenceDataDirectoryEntryReference: CRDDER679
      customerReference: CSRE3456
      socioEconomicClassification: High
      employment: Analyst
      educationHistory: Post Graduate From MIT University
  ReferenceBase:
    type: object
    properties:
      customerReference:
        type: string
        example: CR1234
      customerLegalEntityReference:
        type: string
        example: CS75433
      customerNameSalutation:
        type: string
        example: Mr.John
      governmentIssuedIdentityReference:
        type: string
        example: SocialSecurityNumber
      governmentIssuedDocumentDetails:
        type: string
        example: Passport
      residencyStatus:
        type: string
        example: Own
      dateOfBirth:
        type: string
        example: '1970-08-01'
      nationality:
        type: string
        example: US
      residentialAddress:
        type: string
        example: 23 Dallas Texas
      emailAddress:
        type: string
        example: john@email.co
      cellPhoneNumber:
        type: string
        example: +1-4123464748
      socialNetworkContacts:
        type: string
        example: john@twiiter
      politicalExposureType:
        type: string
        example: Senior
      politicalExposureRecord:
        type: object
        example: PoliticalRecord
        properties: {}
      corporateCustomerReference:
        type: string
        example: CCRE6010
      corporateCustomerLegalEntityReference:
        type: string
        example: CCLE2010
      corporateAddress:
        type: string
        example: 78B Chruch Street  Dallas Texas United States
      companyOfficerRole:
        type: string
        example: Accountant
      companyOfficerReference:
        type: string
        example: CORE1962
      customerSinceDate:
        type: string
        example: '2010-08-01'
      customerReferenceRecord:
        type: object
        properties: {}
    example:
      socialNetworkContacts: john@twiiter
      corporateCustomerLegalEntityReference: CCLE2010
      corporateCustomerReference: CCRE6010
      customerNameSalutation: Mr.John
      companyOfficerReference: CORE1962
      dateOfBirth: '1970-08-01'
      customerReferenceRecord: '{}'
      customerSinceDate: '2010-08-01'
      companyOfficerRole: Accountant
      governmentIssuedIdentityReference: SocialSecurityNumber
      residencyStatus: Own
      emailAddress: john@email.co
      politicalExposureRecord: PoliticalRecord
      corporateAddress: 78B Chruch Street  Dallas Texas United States
      customerLegalEntityReference: CS75433
      nationality: US
      cellPhoneNumber: +1-4123464748
      politicalExposureType: Senior
      customerReference: CR1234
      residentialAddress: 23 Dallas Texas
      governmentIssuedDocumentDetails: Passport
  ReferenceBaseWithIdAndRoot:
    type: object
    properties:
      customerReferenceDataDirectoryEntryReference:
        type: string
        example: CRDDER679
      referenceDirectoryEntryReference:
        type: string
        example: EX7777
      customerReference:
        type: string
        example: CR1234
      customerLegalEntityReference:
        type: string
        example: CS75433
      customerNameSalutation:
        type: string
        example: Mr.John
      governmentIssuedIdentityReference:
        type: string
        example: SocialSecurityNumber
      governmentIssuedDocumentDetails:
        type: string
        example: Passport
      residencyStatus:
        type: string
        example: Own
      dateOfBirth:
        type: string
        example: '1970-08-01'
      nationality:
        type: string
        example: US
      residentialAddress:
        type: string
        example: 23 Dallas Texas
      emailAddress:
        type: string
        example: john@email.co
      cellPhoneNumber:
        type: string
        example: +1-4123464748
      socialNetworkContacts:
        type: string
        example: john@twiiter
      politicalExposureType:
        type: string
        example: Senior
      politicalExposureRecord:
        type: object
        example: PoliticalRecord
        properties: {}
      corporateCustomerReference:
        type: string
        example: CCRE6010
      corporateCustomerLegalEntityReference:
        type: string
        example: CCLE2010
      corporateAddress:
        type: string
        example: 78B Chruch Street  Dallas Texas United States
      companyOfficerRole:
        type: string
        example: Accountant
      companyOfficerReference:
        type: string
        example: CORE1962
      customerSinceDate:
        type: string
        example: '2010-08-01'
      customerReferenceRecord:
        type: object
        properties: {}
    example:
      socialNetworkContacts: john@twiiter
      corporateCustomerLegalEntityReference: CCLE2010
      referenceDirectoryEntryReference: EX7777
      corporateCustomerReference: CCRE6010
      customerNameSalutation: Mr.John
      companyOfficerReference: CORE1962
      dateOfBirth: '1970-08-01'
      customerReferenceRecord: '{}'
      customerSinceDate: '2010-08-01'
      companyOfficerRole: Accountant
      governmentIssuedIdentityReference: SocialSecurityNumber
      residencyStatus: Own
      emailAddress: john@email.co
      politicalExposureRecord: PoliticalRecord
      corporateAddress: 78B Chruch Street  Dallas Texas United States
      customerLegalEntityReference: CS75433
      nationality: US
      cellPhoneNumber: +1-4123464748
      customerReferenceDataDirectoryEntryReference: CRDDER679
      politicalExposureType: Senior
      customerReference: CR1234
      residentialAddress: 23 Dallas Texas
      governmentIssuedDocumentDetails: Passport
  BankRelationsBase:
    type: object
    properties:
      customerReference:
        type: string
        example: CSRE3456
      bankRelationType:
        type: string
        example: Agent
      businessUnitEmployeeReference:
        type: string
        example: BUER2920
    example:
      customerReference: CSRE3456
      businessUnitEmployeeReference: BUER2920
      bankRelationType: Agent
  BankRelationsBaseWithIdAndRoot:
    type: object
    properties:
      customerReferenceDataDirectoryEntryReference:
        type: string
        example: CRDDER679
      bankRelationsDirectoryEntryReference:
        type: string
        example: BR73654
      customerReference:
        type: string
        example: CSRE3456
      bankRelationType:
        type: string
        example: Agent
      businessUnitEmployeeReference:
        type: string
        example: BUER2920
    example:
      customerReferenceDataDirectoryEntryReference: CRDDER679
      customerReference: CSRE3456
      businessUnitEmployeeReference: BUER2920
      bankRelationsDirectoryEntryReference: BR73654
      bankRelationType: Agent
  RetrieveCustomerReferenceDataManagementRoot:
    type: object
    properties:
      customerReferenceDataDirectoryEntryReference:
        type: string
        example: CRDDER679
    example:
      customerReferenceDataDirectoryEntryReference: CRDDER679
  ReferenceBaseUpdateRequest:
    type: object
    properties:
      customerNameSalutation:
        type: string
        example: Mr.John/Mr.Peter
      governmentIssuedIdentityReference:
        type: string
        example: GIIR4001
      governmentIssuedDocumentDetails:
        type: string
        example: SocialSecurityNumber/Passport/DrivingLicense
      residencyStatus:
        type: string
        example: Own/Leased/Rented
      dateOfBirth:
        type: string
        example: '1970-08-01'
      nationality:
        type: string
        example: US/Canada/India
      residentialAddress:
        type: string
        example: 23 Dallas Texas
      emailAddress:
        type: string
        example: john@email.co
      cellPhoneNumber:
        type: string
        example: +1-4123464748
      socialNetworkContacts:
        type: string
        example: john@twiiter/john@facebook
      politicalExposureType:
        type: string
        example: Senior/PoliticalPosition/Exposure
      politicalExposureRecord:
        type: object
        properties: {}
      corporateCustomerReference:
        type: string
        example: CCRE6010
      corporateAddress:
        type: string
        example: 4 Dallas Texas
      companyOfficerRole:
        type: string
        example: Accountant/Consultant/Manager
      companyOfficerReference:
        type: string
        example: CORE1962
      customerSinceDate:
        type: string
        example: '2010-08-01'
      customerReferenceRecord:
        type: object
        properties: {}
    example:
      socialNetworkContacts: john@twiiter/john@facebook
      corporateCustomerReference: CCRE6010
      customerNameSalutation: Mr.John/Mr.Peter
      companyOfficerReference: CORE1962
      dateOfBirth: '1970-08-01'
      customerReferenceRecord: '{}'
      customerSinceDate: '2010-08-01'
      companyOfficerRole: Accountant/Consultant/Manager
      governmentIssuedIdentityReference: GIIR4001
      residencyStatus: Own/Leased/Rented
      emailAddress: john@email.co
      politicalExposureRecord: '{}'
      corporateAddress: 4 Dallas Texas
      nationality: US/Canada/India
      cellPhoneNumber: +1-4123464748
      politicalExposureType: Senior/PoliticalPosition/Exposure
      residentialAddress: 23 Dallas Texas
      governmentIssuedDocumentDetails: SocialSecurityNumber/Passport/DrivingLicense
  CustomerReferenceDataDirectoryReferences:
    type: object
    properties:              
      customerReferenceDataDirectoryEntryReference:
        type: string
        example: CRDDER679
      referenceDirectoryEntryReference:
        type: string
        example: EX7777
      customerReference:
        type: string
        example: CR1234
      customerLegalEntityReference:
        type: string
        example: CS75433
      customerNameSalutation:
        type: string
        example: Mr.John
      governmentIssuedIdentityReference:
        type: string
        example: SocialSecurityNumber
      governmentIssuedDocumentDetails:
        type: string
        example: Passport
      residencyStatus:
        type: string
        example: Own
      dateOfBirth:
        type: string
        example: '1970-08-01'
      nationality:
        type: string
        example: US
      residentialAddress:
        type: string
        example: 23 Dallas Texas
      emailAddress:
        type: string
        example: john@email.co
      cellPhoneNumber:
        type: string
        example: +1-4123464748
      socialNetworkContacts:
        type: string
        example: john@twiiter
      politicalExposureType:
        type: string
        example: Senior
      politicalExposureRecord:
        type: object
        example: PoliticalRecord
        properties: {}
      corporateCustomerReference:
        type: string
        example: CCRE6010
      corporateCustomerLegalEntityReference:
        type: string
        example: CCLE2010
      corporateAddress:
        type: string
        example: 78B Chruch Street  Dallas Texas United States
      companyOfficerRole:
        type: string
        example: Accountant
      companyOfficerReference:
        type: string
        example: CORE1962
      customerSinceDate:
        type: string
        example: '2010-08-01'
      customerReferenceRecord:
        type: object
        properties: {}
  Error:
    type: object
    description: This object represents one or more errors that can be returned by an API.  Each error is made up of an error information section.
    properties:
      errorInfo:
        type: array
        items:
          $ref: '#/definitions/ErrorInfo'
    required:
      - errorInfo
  ErrorInfo:
    type: object
    description: This section contains information about a specific error such as a unique code to identify the error and a textual string to describe the error in more detail.
    properties:
      code:
        type: string
        description: 'The unique error code for the specific error that has occurred, e.g. INT-312. The API Documentation should include a list of error codes and their meaning that an API can return.'
      causes:
        type: array
        description: 'A description field to give more context about the error that has occurred, e.g. The account does not exist'
        items:
          type: string
        minItems: 1
      sourceDetails:
        type: object
        description: A set of data that helps identify the application that generated the error
        properties:
          eimId:
            type: integer
            description: 'The EIM Application Instance Id of the back-end system that generated the error, e.g. 897707.'
          applicationName:
            type: string
            description: The name of the application (API or back-end system) that generated the error.  If the application is in EIM this should be the EIM Application Instance name.
          transactionName:
            type: string
            description: The name of the back-end (mainframe) transaction that generated the error.  Only relevant when a back-end system generates the error.
          layer:
            type: string
            enum:
              - SYSTEM_API
              - PROCESS_API
              - EXPERIENCE_API
              - API
              - BACKEND_SYSTEM
            description: 'Identifies the layer in the architecture that generated the error (API or back-end system).  Valid values: i) SYSTEM_API - an api that is used to expose the data in a system of record in a consistent format to be consumed by a Process API (pAPI) or Experience API (xAPI) as part of the API-led Connectivity integration pattern., ii) PROCESS_API - Process APIs (pAPI) are typically used for composing and orchestrating APIs; they are used for agility and new value creation.  They deliver reusable functionality encapsulated within common cross-functional APIs. iii) EXPERIENCE_API - An Experience API (xAPI) is purpose-built to satisfy a particular consumer, ideally using a technique known as ‘consumer led development’.  This is where the consumer defines what they want to see within the API, and can use agile development methods and rapid-prototyping to quickly define the shape of the API they wish to consume, independently of what underlying APIs are called to access the systems of record. iv) API - if a team does not follow API-led Connectivity then they can use the generic term api. v) BACKEND_SYSTEM - if the error originates from a backend system or fulfillment system.'
        required:
          - applicationName
          - layer
      extendedDetails:
        type: object
        description: 'This object will be populated only when an API needs to provide additional enriching error information. If it is populated then an extended, backward compatible schema should describe the possible fields and how an API client should use them'
      correlationId:
        type: string
        description: A generated UUID for the request that generated this error. Only populated if generated inside the application. CorrelationIDs sent by a provider will not usually be sent back to the API client as they already have this information
      errorStack:
        type: array
        items:
          $ref: '#/definitions/ErrorInfo'
    required:
      - code
      - causes
parameters:
  X-INFOSYS-Locale:
    name: X-INFOSYS-Locale
    in: header
    description: This represents the language of the client and is effectively an internally used Accept-Language Header as governed by RFC 2616
    type: string
    pattern: ^[a-zA-Z0-9,;.=_ -]+$
  X-INFOSYS-Channel-CountryCode:  
    name: X-INFOSYS-Channel-CountryCode
    in: header
    description: This represents the language of the client and is effectively an internally used Accept-Language Header as governed by RFC 2616
    required: true
    type: string  
    pattern: ^[A-Z]{2}$
  X-INFOSYS-Channel-Group-Member:
    name: X-INFOSYS-Channel-Group-Member
    in: header
    description: Legal entity for the Bank within the country.
    required: true
    type: string  
    pattern: ^[A-Z]{4}$
  X-INFOSYS-Channel-Id:
    name: X-INFOSYS-Channel-Id
    in: header
    description: Channel Id
    required: true
    type: string  
    pattern: ^[a-zA-Z0-9]+$
  X-INFOSYS-Src-Device-Id:  
    name: X-INFOSYS-Src-Device-Id
    in: header
    description: Device Id
    required: true
    type: string  
    pattern: ^[a-zA-Z0-9.,:_ -]+$
  X-INFOSYS-Session-Correlation-Id:
    name: X-INFOSYS-Session-Correlation-Id
    in: header
    description: Session Correlation ID to correlate all requests from a user's session
    required: false
    type: string  
  X-INFOSYS-Request-Correlation-Id:
    name: X-INFOSYS-Request-Correlation-Id
    in: header
    description: Request Correlation ID to correlate all messages passed down the estate for a given request from the front-end
    required: true
    type: string  
    pattern: ^[a-zA-Z0-9]+$  