swagger: '2.0'
info:
  version: 1.0.0
  title: Customer Credit Rating
  description: This service domain maintains and administers the bank's credit assessment for customers.
# host: infosys.com
# basePath: /customer-credit-rating/v1
securityDefinitions:
  apiClientID:
    type: apiKey
    in: header
    name: X-INFOSYS-Client-Id
    description: The client id obtained from the API manager. This client id must have been registered to use this API by requesting access to it.
  apiClientSecret:
    type: apiKey
    in: header
    name: X-INFOSYS-Client-secret
    description: The client id obtained from the API manager. This client id must have been registered to use this API by requesting access to it.
  apiSecurityToken:
    type: apiKey
    in: header
    name: X-INFOSYS-SECURE-TOKEN
    description: The SAML or JWT end to end trust token retreived from IDAM
security:
  - apiClientID: []
    apiClientSecret: []
  - apiSecurityToken: []
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  '/customers/{customer-id}/alerts':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    post:
      tags:
        - record
      summary: Record information against Customer Credit Rating alert
      operationId: recordCustomerCreditRatingMeasurementAlert
      parameters:
        - name: customer-id
          in: path
          description: Customer Credit Rating Assessment Reference
          required: true
          type: string
        - in: body
          name: body
          description: Customer Credit Rating Alert Request Payload
          required: false
          schema:
            $ref: '#/definitions/AlertRecordRequest'
      responses:
        '201':
          description: Created a Customer Credit Rating Alert record successfully
          schema:
            $ref: '#/definitions/AlertRecordResponse'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'     
  '/customers/{customer-id}/assessment':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    post:
      tags:
        - record
      summary: Record information against Customer Credit Rating assessment
      operationId: recordCustomerCreditRatingMeasurement
      parameters:
        - name: customer-id
          in: path
          description: Customer Credit Rating Assessment Reference
          required: true
          type: string
        - in: body
          name: body
          description: Record Request Payload
          required: true
          schema:
            $ref: '#/definitions/CreditRatingRecordRequest'
      responses:
        '201':
          description: Created a Customer Credit Rating record successfully
          schema:
            $ref: '#/definitions/CreditRatingRecordResponse'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'     
  '/customers/{customer-id}/requisition':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    put:
      tags:
        - request
      summary: update Request to undertake credit view refresh/reworking
      operationId: requestCustomerCreditRatingMeasurementUpdate
      parameters:
        - name: customer-id
          in: path
          description: Customer Credit Rating Assessment Reference
          required: true
          type: string
        - in: body
          name: body
          description: Customer Credit Assessment Request Payload
          required: true
          schema:
            $ref: '#/definitions/CreditRatingBase'
      responses:
        '200':
          description: Updated a Customer Credit Rating record successfully
          schema:
            $ref: '#/definitions/CreditRatingBaseWithId'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'     
  /customers/requisition:
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'  
    post:
      tags:
        - request
      summary: Create Request to undertake credit view refresh/reworking
      operationId: requestCustomerCreditRatingMeasurementCreate
      parameters:
        - in: body
          name: body
          description: Customer Credit Assessment Request Payload
          required: true
          schema:
            $ref: '#/definitions/CreditRatingBase'
      responses:
        '201':
          description: Created a Customer Credit Rating record successfully
          schema:
            $ref: '#/definitions/CreditRatingBaseWithId'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'     
  /customers/measurement:
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    get:
      tags:
        - retrieve
      summary: Retrieve Customer Credit Rating  Control Record Ids available within the Service Domain.
      operationId: retrieveCustomerCreditRatingMeasurementReferenceIds
      produces:
        - application/json
      parameters:
        - name: collection-filter
          in: query
          description: Filter to refine the result set. ex- 'customerBehaviorModel = CBM123'
          required: false
          type: string
      responses:
        '200':
          description: successful
          schema:
            type: array
            items:
              type: string
            example:
              - CCR123
              - CCR345
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'     
  /customers/measurement/behavior-qualifiers:
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    get:
      tags:
        - retrieve
      summary: Retrieve all Behaviour Qualifier names in Customer Credit Rating Domain.
      operationId: retrieveCustomerCreditRatingMeasurementBehaviorQualifiers
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: Retrieved all Behaviour Qualifier names in Customer Credit Rating Domain successfully
          schema:
            type: array
            items:
              type: string
            example:
              - external-rating
              - internal-analysis
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'     
  '/customers/measurement/{customer-id}/{behavior-qualifier}':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    get:
      tags:
        - retrieve
      summary: Retrieve Behaviour Qualifier Reference Ids of a given Behavior Qulifier.
      operationId: RetrieveBehaviorQualifierReferenceIds
      produces:
        - application/json
      parameters:
        - name: customer-id
          in: path
          description: Customer Credit Rating Assessment Reference
          required: true
          type: string
        - name: behavior-qualifier
          in: path
          description: Behavior Qualifier Name. ex- external-rating
          required: true
          type: string
        - name: collection-filter
          in: query
          description: Filter to refine the result set. ex- 'ratingAgencyCreditReportType = type-1'
          required: false
          type: string
      responses:
        '200':
          description: successful
          schema:
            type: array
            items:
              type: string
            example:
              - ER345
              - ER789
              - ER456
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'     
  '/customers/measurement/{customer-id}':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    get:
      tags:
        - retrieve
      summary: Customer Credit Rating Assessment record
      operationId: retrieveCustomerCreditRatingMeasurement
      parameters:
        - name: customer-id
          in: path
          description: Customer Credit Rating Assessment Reference
          required: true
          type: string
      responses:
        '200':
          description: Retrieved Customer Credit Rating Assessment record successfully
          schema:
            $ref: '#/definitions/CreditRatingBaseWithId'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'     
  '/customers/measurement/{customer-id}/alerts/{bq-reference-id}':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    get:
      tags:
        - retrieve
      summary: Retrieve Alerts Behaviour Qualifier with all its' attributes.
      operationId: Retrievealerts
      produces:
        - application/json
      parameters:
        - name: customer-id
          in: path
          description: Customer Credit Rating Assessment Reference
          required: true
          type: string
        - name: bq-reference-id
          in: path
          description: Rating Agency Credit Report Reference
          required: true
          type: string
      responses:
        '200':
          description: Retrieved Customer Credit Alerts record successfully
          schema:
            $ref: '#/definitions/CreditRatingAlerts'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'     
  '/customers/measurement/{customer-id}/external-ratings/{bq-reference-id}':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    get:
      tags:
        - retrieve
      summary: Retrieve External Rating Behaviour Qualifier with all its' attributes.
      operationId: Retrieveexternalratings
      produces:
        - application/json
      parameters:
        - name: customer-id
          in: path
          description: Customer Credit Rating Assessment Reference
          required: true
          type: string
        - name: bq-reference-id
          in: path
          description: Rating Agency Credit Report Reference
          required: true
          type: string
      responses:
        '200':
          description: Retrieved Customer Credit External Rating record successfully
          schema:
            $ref: '#/definitions/CreditRatingExternalRating'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'     
  '/customers/measurement/{customer-id}/internal-analysis/{bq-reference-id}':
    parameters: 
      - $ref: '#/parameters/X-INFOSYS-Locale' 
      - $ref: '#/parameters/X-INFOSYS-Channel-CountryCode'
      - $ref: '#/parameters/X-INFOSYS-Channel-Group-Member'
      - $ref: '#/parameters/X-INFOSYS-Channel-Id'
      - $ref: '#/parameters/X-INFOSYS-Src-Device-Id'
      - $ref: '#/parameters/X-INFOSYS-Session-Correlation-Id'
      - $ref: '#/parameters/X-INFOSYS-Request-Correlation-Id'
    get:
      tags:
        - retrieve
      summary: Retrieve Internal Analysis Behaviour Qualifier with all its' attributes.
      operationId: Retrieveinternalanalysis
      produces:
        - application/json
      parameters:
        - name: customer-id
          in: path
          description: Customer Credit Rating Assessment Reference
          required: true
          type: string
        - name: bq-reference-id
          in: path
          description: Internal Credit Analysis Report Reference
          required: true
          type: string
      responses:
        '200':
          description: Retrieved Customer Credit Internal Analysis record successfully
          schema:
            $ref: '#/definitions/CreditRatingInternalAnalysisBase'
        '400':
          description: Bad request - fields missing or in wrong format.
          schema:
            $ref: '#/definitions/Error'  
        '401':
          description: Authorisation failure.
        '403':
          description: Authentication failure.
        '404':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'  
        '405':
          description: URI not found.
          schema:
            $ref: '#/definitions/Error'    
        '406':
          description: Not acceptable.
          schema:
              $ref: '#/definitions/Error' 
        '415':
          description: Unsupported media type
          schema:
              $ref: '#/definitions/Error' 
        '429':
          description: Too Many Requests.    
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error' 
        '503':
          description: Service unavailable
        '504':
          description: backend timeout
          schema:
              $ref: '#/definitions/Error'     
definitions:
  CreditRatingAlerts:
    properties:
      customerCreditAlertReference:
        type: string
        example: CCRAR232342
      customerReference:
        type: string
        example: CCRAR232342
      customerCreditRatingAssessmentReference:
        type: string
        example: CCRAR232342
      productInstanceReference:
        type: string
        example: CCRAR232342
      employeeBusinessUnitReference:
        type: string
        example: CCRAR232342
      customerCreditAlertType:
        type: string
        example: CCRAR232342
      customerCreditAlertDescription:
        type: string
        example: Customer Credit Alert
      dateTime:
        type: string
        example: '2018-09-06T09:00:00'
    example:
      dateTime: '2018-09-06T09:00:00'
      productInstanceReference: CCRAR232342
      employeeBusinessUnitReference: CCRAR232342
      customerReference: CCRAR232342
      customerCreditAlertDescription: Customer Credit Alert
      customerCreditAlertReference: CCRAR232342
      customerCreditRatingAssessmentReference: CCRAR232342
      customerCreditAlertType: CCRAR232342
  CreditRatingExternalRating:
    properties:
      customerCreditRatingAssessmentReference:
        type: string
        example: CCRAR232342
      ratingAgencyReference:
        type: string
        example: RAR888
      ratingAgencyAccessServiceSessionReference:
        type: string
        example: RAASSR237
      ratingAgencyAccessSchedule:
        type: string
        example: service availability
      customerReference:
        type: string
        example: CR568
      ratingAgencyCreditReportType:
        type: string
        example: long/short form report
      ratingAgencyCreditReportReference:
        type: string
        example: RACRR432
      ratingAgencyCreditReport:
        type: object
        properties: {}
      ratingAgengyCreditReportDateTime:
        type: string
        example: '2018-09-06T09:00:00'
    example:
      ratingAgencyCreditReportType: long/short form report
      ratingAgencyCreditReport: '{}'
      ratingAgengyCreditReportDateTime: '2018-09-06T09:00:00'
      ratingAgencyCreditReportReference: RACRR432
      customerReference: CR568
      ratingAgencyAccessServiceSessionReference: RAASSR237
      ratingAgencyAccessSchedule: service availability
      customerCreditRatingAssessmentReference: CCRAR232342
      ratingAgencyReference: RAR888
  CreditRatingInternalAnalysisBase:
    type: object
    properties:
      customerCreditRatingAssessmentReference:
        type: string
        example: CCRAR232342
      internalCreditAnalysisReportReference:
        type: string
        example: ICARR23476
      productServiceActivityReportReference:
        type: string
        example: PSARR4567
      productServiceActivityReport:
        type: string
        example: PSAR132
      customerReference:
        type: string
        example: CR987
      customerBehaviorModel:
        type: string
        example: CBM777
      internalCreditAnalysisReportType:
        type: string
        example: ICART23476
      internalCreditAnalysisReport:
        type: string
        example: ICAR23476
      internalCreditAnalysisReportDateTime:
        type: string
        example: '2018-09-06T09:00:00'
    example:
      internalCreditAnalysisReport: ICAR23476
      internalCreditAnalysisReportDateTime: '2018-09-06T09:00:00'
      internalCreditAnalysisReportReference: ICARR23476
      internalCreditAnalysisReportType: ICART23476
      customerReference: CR987
      customerCreditRatingAssessmentReference: CCRAR232342
      productServiceActivityReportReference: PSARR4567
      customerBehaviorModel: CBM777
      productServiceActivityReport: PSAR132
  CreditRatingBaseWithId:
    properties:
      customerCreditRatingAssessmentReference:
        type: string
        example: CCRAR232342
      customerCreditRatingAssessment:
        type: string
        example: internal bank credit rating/assessment
      customerBehaviorModel:
        type: string
        example: model2
      ratingAgencyCreditReportReference:
        type: string
        example: RRCRR436
      internalCreditAnalysisReportReference:
        type: string
        example: ICARR9090
      customerReference:
        type: string
        example: CR437
      customerCreditRatingAssessmentType:
        type: string
        example: corporate
      customerCreditRatingNarrative:
        type: string
        example: structured report outlining basis for rating
      customerCreditRatingSchedule:
        type: string
        example: update schedule
    example:
      customerCreditRatingSchedule: update schedule
      customerCreditRatingAssessment: internal bank credit rating/assessment
      internalCreditAnalysisReportReference: ICARR9090
      ratingAgencyCreditReportReference: RRCRR436
      customerReference: CR437
      customerCreditRatingNarrative: structured report outlining basis for rating
      customerCreditRatingAssessmentType: corporate
      customerCreditRatingAssessmentReference: CCRAR232342
      customerBehaviorModel: model2
  AlertRecordRequest:
    type: object
    properties:
      customerReference:
        type: string
        example: CR564
      customerCreditRatingAssessmentReference:
        type: string
        example: CCRAR232342
      productInstanceReference:
        type: string
        example: PIR7676
      employeeBusinessUnitReference:
        type: string
        example: EBUR5567
      customerCreditAlertType:
        type: string
        example: CCAT678
      customerCreditAlertDescription:
        type: string
        example: Alert
      dateTime:
        type: string
        example: '2018-09-06T09:00:00'
    example:
      dateTime: '2018-09-06T09:00:00'
      productInstanceReference: PIR7676
      employeeBusinessUnitReference: EBUR5567
      customerReference: CR564
      customerCreditAlertDescription: Alert
      customerCreditRatingAssessmentReference: CCRAR232342
      customerCreditAlertType: CCAT678
  AlertRecordResponse:
    type: object
    properties:
      customerCreditAlertReference:
        type: string
        example: CCAR2342
      recordingRecordStatus:
        type: string
        example: Applied
    example:
      customerCreditAlertReference: CCAR2342
      recordingRecordStatus: Applied
  CreditRatingBase:
    properties:
      customerCreditRatingAssessment:
        type: string
        example: internal bank credit rating/assessment
      customerBehaviorModel:
        type: string
        example: model2
      ratingAgencyCreditReportReference:
        type: string
        example: RACRR538
      internalCreditAnalysisReportReference:
        type: string
        example: ICARR980
      customerReference:
        type: string
        example: CR1234
      customerCreditRatingAssessmentType:
        type: string
        example: corporate
      customerCreditRatingNarrative:
        type: string
        example: structured report outlining basis for rating
      customerCreditRatingSchedule:
        type: string
        example: update schedule
    example:
      customerCreditRatingSchedule: update schedule
      customerCreditRatingAssessment: internal bank credit rating/assessment
      internalCreditAnalysisReportReference: ICARR980
      ratingAgencyCreditReportReference: RACRR538
      customerReference: CR1234
      customerCreditRatingNarrative: structured report outlining basis for rating
      customerCreditRatingAssessmentType: corporate
      customerBehaviorModel: model2
  CreditRatingRecordRequest:
    type: object
    properties:
      recordingRecordType:
        type: string
        example: Behavior model performance feedback
      recordingRecord:
        type: object
        properties: {}
      recordingRecordDateTime:
        type: string
        example: '2018-09-06T09:00:00'
      employeeBusinessUnitReference:
        type: string
        example: REF456
    example:
      recordingRecordType: Behavior model performance feedback
      employeeBusinessUnitReference: REF456
      recordingRecordDateTime: '2018-09-06T09:00:00'
      recordingRecord: '{}'
  CreditRatingRecordResponse:
    type: object
    properties:
      recordingRecordReference:
        type: string
        example: RRR4678
      recordingRecordStatus:
        type: string
        example: Applied
    example:
      recordingRecordReference: RRR4678
      recordingRecordStatus: Applied
  Error:
    type: object
    description: This object represents one or more errors that can be returned by an API.  Each error is made up of an error information section.
    properties:
      errorInfo:
        type: array
        items:
          $ref: '#/definitions/ErrorInfo'
    required:
      - errorInfo
  ErrorInfo:
    type: object
    description: This section contains information about a specific error such as a unique code to identify the error and a textual string to describe the error in more detail.
    properties:
      code:
        type: string
        description: 'The unique error code for the specific error that has occurred, e.g. INT-312. The API Documentation should include a list of error codes and their meaning that an API can return.'
      causes:
        type: array
        description: 'A description field to give more context about the error that has occurred, e.g. The account does not exist'
        items:
          type: string
        minItems: 1
      sourceDetails:
        type: object
        description: A set of data that helps identify the application that generated the error
        properties:
          eimId:
            type: integer
            description: 'The EIM Application Instance Id of the back-end system that generated the error, e.g. 897707.'
          applicationName:
            type: string
            description: The name of the application (API or back-end system) that generated the error.  If the application is in EIM this should be the EIM Application Instance name.
          transactionName:
            type: string
            description: The name of the back-end (mainframe) transaction that generated the error.  Only relevant when a back-end system generates the error.
          layer:
            type: string
            enum:
              - SYSTEM_API
              - PROCESS_API
              - EXPERIENCE_API
              - API
              - BACKEND_SYSTEM
            description: 'Identifies the layer in the architecture that generated the error (API or back-end system).  Valid values: i) SYSTEM_API - an api that is used to expose the data in a system of record in a consistent format to be consumed by a Process API (pAPI) or Experience API (xAPI) as part of the API-led Connectivity integration pattern., ii) PROCESS_API - Process APIs (pAPI) are typically used for composing and orchestrating APIs; they are used for agility and new value creation.  They deliver reusable functionality encapsulated within common cross-functional APIs. iii) EXPERIENCE_API - An Experience API (xAPI) is purpose-built to satisfy a particular consumer, ideally using a technique known as ‘consumer led development’.  This is where the consumer defines what they want to see within the API, and can use agile development methods and rapid-prototyping to quickly define the shape of the API they wish to consume, independently of what underlying APIs are called to access the systems of record. iv) API - if a team does not follow API-led Connectivity then they can use the generic term api. v) BACKEND_SYSTEM - if the error originates from a backend system or fulfillment system.'
        required:
          - applicationName
          - layer
      extendedDetails:
        type: object
        description: 'This object will be populated only when an API needs to provide additional enriching error information. If it is populated then an extended, backward compatible schema should describe the possible fields and how an API client should use them'
      correlationId:
        type: string
        description: A generated UUID for the request that generated this error. Only populated if generated inside the application. CorrelationIDs sent by a provider will not usually be sent back to the API client as they already have this information
      errorStack:
        type: array
        items:
          $ref: '#/definitions/ErrorInfo'
    required:
      - code
      - causes
parameters:
  X-INFOSYS-Locale:
    name: X-INFOSYS-Locale
    in: header
    description: This represents the language of the client and is effectively an internally used Accept-Language Header as governed by RFC 2616
    type: string
    pattern: ^[a-zA-Z0-9,;.=_ -]+$
  X-INFOSYS-Channel-CountryCode:  
    name: X-INFOSYS-Channel-CountryCode
    in: header
    description: This represents the language of the client and is effectively an internally used Accept-Language Header as governed by RFC 2616
    required: true
    type: string  
    pattern: ^[A-Z]{2}$
  X-INFOSYS-Channel-Group-Member:
    name: X-INFOSYS-Channel-Group-Member
    in: header
    description: Legal entity for the Bank within the country.
    required: true
    type: string  
    pattern: ^[A-Z]{4}$
  X-INFOSYS-Channel-Id:
    name: X-INFOSYS-Channel-Id
    in: header
    description: Channel Id
    required: true
    type: string  
    pattern: ^[a-zA-Z0-9]+$
  X-INFOSYS-Src-Device-Id:  
    name: X-INFOSYS-Src-Device-Id
    in: header
    description: Device Id
    required: true
    type: string  
    pattern: ^[a-zA-Z0-9.,:_ -]+$
  X-INFOSYS-Session-Correlation-Id:
    name: X-INFOSYS-Session-Correlation-Id
    in: header
    description: Session Correlation ID to correlate all requests from a user's session
    required: false
    type: string  
  X-INFOSYS-Request-Correlation-Id:
    name: X-INFOSYS-Request-Correlation-Id
    in: header
    description: Request Correlation ID to correlate all messages passed down the estate for a given request from the front-end
    required: true
    type: string  
    pattern: ^[a-zA-Z0-9]+$
# Added by API Auto Mocking Plugin
host: infyapi.ad.infosys.com
basePath: /virts/Aparna_Y/CustomerCreditRatingAPI/1.0.0